# Generated by Django 4.1.2 on 2022-10-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    def seed_polls(apps, schema_editor):
        Poll = apps.get_model('service', 'Poll')
        Poll(url='https://api.cryptowat.ch/markets/kraken/btceur/price',interval_ms=60000)

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_polls),
    ]
